# This is a basic workflow to help you get started with Actions

name: Azure Bicep Deployment

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  Lint:
    name: 'AzureBicepDeploy'
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: techielassinc-bicep-rg
      ResourceGroupLocation: "uksouth"
    environment: production
 
    steps:
    - uses: actions/checkout@v3.3.0

    - name: Run Bicep linter
      run: az bicep build --file ./Module/main.bicep
 




 
